# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QMenu, QMenuBar, QPlainTextEdit, QSizePolicy,
    QSplitter, QTabWidget, QToolBar, QVBoxLayout,
    QWidget)
from  . import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        icon = QIcon()
        icon.addFile(u":/icons/icons/program_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QSize(26, 26))
        self.a_new_project = QAction(MainWindow)
        self.a_new_project.setObjectName(u"a_new_project")
        icon1 = QIcon()
        icon1.addFile(u":/icons/icons/new_project.png", QSize(), QIcon.Normal, QIcon.Off)
        self.a_new_project.setIcon(icon1)
        self.a_duplicate_project = QAction(MainWindow)
        self.a_duplicate_project.setObjectName(u"a_duplicate_project")
        icon2 = QIcon()
        icon2.addFile(u":/icons/icons/duplicate_project.png", QSize(), QIcon.Normal, QIcon.Off)
        self.a_duplicate_project.setIcon(icon2)
        self.a_save_project = QAction(MainWindow)
        self.a_save_project.setObjectName(u"a_save_project")
        icon3 = QIcon()
        icon3.addFile(u":/icons/icons/save_project.png", QSize(), QIcon.Normal, QIcon.Off)
        self.a_save_project.setIcon(icon3)
        self.a_exit_program = QAction(MainWindow)
        self.a_exit_program.setObjectName(u"a_exit_program")
        icon4 = QIcon()
        icon4.addFile(u":/icons/icons/exit_program.png", QSize(), QIcon.Normal, QIcon.Off)
        self.a_exit_program.setIcon(icon4)
        self.a_about = QAction(MainWindow)
        self.a_about.setObjectName(u"a_about")
        icon5 = QIcon()
        icon5.addFile(u":/icons/icons/about.png", QSize(), QIcon.Normal, QIcon.Off)
        self.a_about.setIcon(icon5)
        self.a_app_settings = QAction(MainWindow)
        self.a_app_settings.setObjectName(u"a_app_settings")
        icon6 = QIcon()
        icon6.addFile(u":/icons/icons/settings.png", QSize(), QIcon.Normal, QIcon.Off)
        self.a_app_settings.setIcon(icon6)
        self.a_open_project = QAction(MainWindow)
        self.a_open_project.setObjectName(u"a_open_project")
        icon7 = QIcon()
        icon7.addFile(u":/icons/icons/open_project.png", QSize(), QIcon.Normal, QIcon.Off)
        self.a_open_project.setIcon(icon7)
        self.a_color_picker = QAction(MainWindow)
        self.a_color_picker.setObjectName(u"a_color_picker")
        icon8 = QIcon()
        icon8.addFile(u":/icons/icons/color_picker.png", QSize(), QIcon.Normal, QIcon.Off)
        self.a_color_picker.setIcon(icon8)
        self.a_file_selector = QAction(MainWindow)
        self.a_file_selector.setObjectName(u"a_file_selector")
        icon9 = QIcon()
        icon9.addFile(u":/icons/icons/file_selector.png", QSize(), QIcon.Normal, QIcon.Off)
        self.a_file_selector.setIcon(icon9)
        self.a_add_code_block = QAction(MainWindow)
        self.a_add_code_block.setObjectName(u"a_add_code_block")
        icon10 = QIcon()
        icon10.addFile(u":/icons/icons/new_code_block.png", QSize(), QIcon.Normal, QIcon.Off)
        self.a_add_code_block.setIcon(icon10)
        self.a_add_text_block = QAction(MainWindow)
        self.a_add_text_block.setObjectName(u"a_add_text_block")
        icon11 = QIcon()
        icon11.addFile(u":/icons/icons/add_text_block.png", QSize(), QIcon.Normal, QIcon.Off)
        self.a_add_text_block.setIcon(icon11)
        self.a_stop_execution = QAction(MainWindow)
        self.a_stop_execution.setObjectName(u"a_stop_execution")
        icon12 = QIcon()
        icon12.addFile(u":/icons/icons/stop_execution.png", QSize(), QIcon.Normal, QIcon.Off)
        self.a_stop_execution.setIcon(icon12)
        self.a_clear_outputs = QAction(MainWindow)
        self.a_clear_outputs.setObjectName(u"a_clear_outputs")
        icon13 = QIcon()
        icon13.addFile(u":/icons/icons/clear_outputs.png", QSize(), QIcon.Normal, QIcon.Off)
        self.a_clear_outputs.setIcon(icon13)
        self.a_restart_kernel = QAction(MainWindow)
        self.a_restart_kernel.setObjectName(u"a_restart_kernel")
        icon14 = QIcon()
        icon14.addFile(u":/icons/icons/restart_kernel.png", QSize(), QIcon.Normal, QIcon.Off)
        self.a_restart_kernel.setIcon(icon14)
        self.a_close_project = QAction(MainWindow)
        self.a_close_project.setObjectName(u"a_close_project")
        icon15 = QIcon()
        icon15.addFile(u":/icons/icons/close_project.png", QSize(), QIcon.Normal, QIcon.Off)
        self.a_close_project.setIcon(icon15)
        self.a_run_selected_blocks = QAction(MainWindow)
        self.a_run_selected_blocks.setObjectName(u"a_run_selected_blocks")
        icon16 = QIcon()
        icon16.addFile(u":/icons/icons/run.png", QSize(), QIcon.Normal, QIcon.Off)
        self.a_run_selected_blocks.setIcon(icon16)
        self.a_delete_selected_blocks = QAction(MainWindow)
        self.a_delete_selected_blocks.setObjectName(u"a_delete_selected_blocks")
        icon17 = QIcon()
        icon17.addFile(u":/icons/icons/delete.png", QSize(), QIcon.Normal, QIcon.Off)
        self.a_delete_selected_blocks.setIcon(icon17)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Vertical)
        self.tab_widget = QTabWidget(self.splitter)
        self.tab_widget.setObjectName(u"tab_widget")
        self.splitter.addWidget(self.tab_widget)
        self.log = QPlainTextEdit(self.splitter)
        self.log.setObjectName(u"log")
        self.log.setMaximumSize(QSize(16777215, 100))
        self.log.setFrameShape(QFrame.Box)
        self.log.setFrameShadow(QFrame.Raised)
        self.log.setReadOnly(True)
        self.log.setTextInteractionFlags(Qt.TextSelectableByMouse)
        self.splitter.addWidget(self.log)

        self.verticalLayout.addWidget(self.splitter)

        self.status_label = QLabel(self.centralwidget)
        self.status_label.setObjectName(u"status_label")

        self.verticalLayout.addWidget(self.status_label)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 17))
        self.project_menu = QMenu(self.menubar)
        self.project_menu.setObjectName(u"project_menu")
        self.help_menu = QMenu(self.menubar)
        self.help_menu.setObjectName(u"help_menu")
        self.instruments_menu = QMenu(self.menubar)
        self.instruments_menu.setObjectName(u"instruments_menu")
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.project_menu.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.instruments_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())
        self.project_menu.addAction(self.a_new_project)
        self.project_menu.addAction(self.a_open_project)
        self.project_menu.addAction(self.a_save_project)
        self.project_menu.addSeparator()
        self.project_menu.addAction(self.a_duplicate_project)
        self.project_menu.addAction(self.a_close_project)
        self.project_menu.addSeparator()
        self.project_menu.addAction(self.a_app_settings)
        self.project_menu.addSeparator()
        self.project_menu.addAction(self.a_exit_program)
        self.help_menu.addAction(self.a_about)
        self.instruments_menu.addAction(self.a_color_picker)
        self.instruments_menu.addAction(self.a_file_selector)
        self.menu.addAction(self.a_add_code_block)
        self.menu.addAction(self.a_add_text_block)
        self.menu.addSeparator()
        self.menu.addAction(self.a_run_selected_blocks)
        self.menu.addAction(self.a_stop_execution)
        self.menu.addAction(self.a_restart_kernel)
        self.menu.addAction(self.a_clear_outputs)
        self.menu.addAction(self.a_delete_selected_blocks)
        self.toolBar.addAction(self.a_new_project)
        self.toolBar.addAction(self.a_open_project)
        self.toolBar.addAction(self.a_save_project)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.a_duplicate_project)
        self.toolBar.addAction(self.a_close_project)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.a_app_settings)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.a_add_code_block)
        self.toolBar.addAction(self.a_add_text_block)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.a_run_selected_blocks)
        self.toolBar.addAction(self.a_stop_execution)
        self.toolBar.addAction(self.a_restart_kernel)
        self.toolBar.addAction(self.a_clear_outputs)
        self.toolBar.addAction(self.a_delete_selected_blocks)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.a_color_picker)
        self.toolBar.addAction(self.a_file_selector)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.a_about)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u041a\u043e\u043d\u0441\u0442\u0440\u0443\u043a\u0442\u043e\u0440 \u043d\u0435\u0439\u0440\u043e\u043d\u043d\u044b\u0445 \u0441\u0435\u0442\u0435\u0439", None))
        self.a_new_project.setText(QCoreApplication.translate("MainWindow", u"\u041d\u043e\u0432\u044b\u0439 \u043f\u0440\u043e\u0435\u043a\u0442", None))
        self.a_duplicate_project.setText(QCoreApplication.translate("MainWindow", u"\u0414\u0443\u0431\u043b\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u0442\u0435\u043a\u0443\u0449\u0438\u0439 \u043f\u0440\u043e\u0435\u043a\u0442", None))
        self.a_save_project.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043f\u0440\u043e\u0435\u043a\u0442", None))
#if QT_CONFIG(shortcut)
        self.a_save_project.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.a_exit_program.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0439\u0442\u0438", None))
        self.a_about.setText(QCoreApplication.translate("MainWindow", u"\u041e \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435", None))
        self.a_app_settings.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u044f", None))
        self.a_open_project.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u043a\u0440\u044b\u0442\u044c \u043f\u0440\u043e\u0435\u043a\u0442", None))
#if QT_CONFIG(shortcut)
        self.a_open_project.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.a_color_picker.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0431\u043e\u0440 \u0446\u0432\u0435\u0442\u0430", None))
        self.a_file_selector.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0431\u043e\u0440 \u0444\u0430\u0439\u043b\u043e\u0432", None))
        self.a_add_code_block.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0431\u043b\u043e\u043a \u043a\u043e\u0434\u0430", None))
#if QT_CONFIG(shortcut)
        self.a_add_code_block.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+B", None))
#endif // QT_CONFIG(shortcut)
        self.a_add_text_block.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0442\u0435\u043a\u0441\u0442\u043e\u0432\u044b\u0439 \u0431\u043b\u043e\u043a", None))
#if QT_CONFIG(shortcut)
        self.a_add_text_block.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
        self.a_stop_execution.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0441\u0442\u0430\u043d\u043e\u0432\u0438\u0442\u044c \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0435 \u0432\u0441\u0435\u0445 \u0431\u043b\u043e\u043a\u043e\u0432", None))
        self.a_clear_outputs.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0447\u0438\u0441\u0442\u0438\u0442\u044c \u0432\u044b\u0432\u043e\u0434 \u0432\u044b\u0431\u0440\u0430\u043d\u043d\u044b\u0445 \u0431\u043b\u043e\u043a\u043e\u0432", None))
        self.a_restart_kernel.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0435\u0440\u0435\u0437\u0430\u043f\u0443\u0441\u0442\u0438\u0442\u044c \u044f\u0434\u0440\u043e", None))
        self.a_close_project.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u043a\u0440\u044b\u0442\u044c \u043f\u0440\u043e\u0435\u043a\u0442", None))
        self.a_run_selected_blocks.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u043f\u0443\u0441\u0442\u0438\u0442\u044c \u0432\u044b\u0431\u0440\u0430\u043d\u043d\u044b\u0435 \u0431\u043b\u043e\u043a\u0438", None))
#if QT_CONFIG(shortcut)
        self.a_run_selected_blocks.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.a_delete_selected_blocks.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0432\u044b\u0431\u0440\u0430\u043d\u043d\u044b\u0435 \u0431\u043b\u043e\u043a\u0438", None))
        self.status_label.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0442\u0430\u0442\u0443\u0441 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0439 \u043e\u043f\u0435\u0440\u0430\u0446\u0438\u0438", None))
        self.project_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u041f\u0440\u043e\u0435\u043a\u0442", None))
        self.help_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u043c\u043e\u0449\u044c", None))
        self.instruments_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u0418\u043d\u0441\u0442\u0440\u0443\u043c\u0435\u043d\u0442\u044b", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u041e\u043f\u0435\u0440\u0430\u0446\u0438\u0438", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

